# Generated by Django 4.2 on 2026-03-26 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание страницы')),
                ('consent_file', models.FileField(blank=True, null=True, upload_to='consent/', verbose_name='Бланк заявления на согласие')),
            ],
            options={
                'verbose_name': 'Оформление согласия',
                'verbose_name_plural': 'Оформление согласия',
            },
        ),
        migrations.CreateModel(
            name='DocumentsPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание страницы (HTML)')),
            ],
            options={
                'verbose_name': 'Страница документов',
                'verbose_name_plural': 'Страница документов',
            },
        ),
        migrations.CreateModel(
            name='DrivingSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=200, verbose_name='Название автомобиля')),
                ('reg_number', models.CharField(max_length=50, verbose_name='Гос.номер')),
                ('schedule_file', models.FileField(upload_to='driving_schedules/', verbose_name='Файл графика')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала действия')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'График вождения',
                'verbose_name_plural': 'Графики вождения',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DrivingScheduleHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ГРАФИКИ ВОЖДЕНИЯ КАТ В с 15.12.2025', max_length=300, verbose_name='Заголовок')),
            ],
            options={
                'verbose_name': 'Заголовок графиков вождения',
                'verbose_name_plural': 'Заголовок графиков вождения',
            },
        ),
        migrations.CreateModel(
            name='EnrollmentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(choices=[('winter', 'Зимний'), ('spring', 'Весенний'), ('summer', 'Летний'), ('autumn', 'Осенний')], max_length=20, verbose_name='Сезон')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('status', models.CharField(choices=[('recording', 'Идёт запись'), ('completed', 'Набор завершен'), ('training', 'Идёт обучение')], default='recording', max_length=20, verbose_name='Статус')),
                ('recording_start', models.DateField(blank=True, null=True, verbose_name='Начало записи')),
                ('recording_end', models.DateField(blank=True, null=True, verbose_name='Конец записи')),
                ('training_start', models.DateField(blank=True, null=True, verbose_name='Начало обучения')),
                ('med_commission_start', models.DateField(blank=True, null=True, verbose_name='Медкомиссия с')),
                ('med_commission_end', models.DateField(blank=True, null=True, verbose_name='Медкомиссия по')),
                ('additional_info', models.TextField(blank=True, verbose_name='Дополнительная информация')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
            ],
            options={
                'verbose_name': 'Период набора',
                'verbose_name_plural': 'Периоды набора',
                'ordering': ['-order', '-year'],
            },
        ),
        migrations.CreateModel(
            name='ExamDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=50, verbose_name='Номер группы')),
                ('exam_date', models.DateField(verbose_name='Дата экзамена')),
                ('exam_time', models.TimeField(verbose_name='Время экзамена')),
                ('classroom', models.CharField(max_length=50, verbose_name='Кабинет')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Дата выпускного экзамена',
                'verbose_name_plural': 'Даты выпускного экзамена',
                'ordering': ['order', 'exam_date'],
            },
        ),
        migrations.CreateModel(
            name='FeeInfoPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание страницы (HTML)')),
            ],
            options={
                'verbose_name': 'Страница госпошлины',
                'verbose_name_plural': 'Страница госпошлины',
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория галереи',
                'verbose_name_plural': 'Категории галереи',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GibddExamDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(max_length=50, verbose_name='Номер группы')),
                ('exam_date', models.DateField(verbose_name='Дата экзамена')),
                ('exam_time', models.TimeField(verbose_name='Время экзамена')),
                ('additional_info', models.CharField(blank=True, max_length=300, verbose_name='Дополнительная информация')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Дата экзамена ГИБДД',
                'verbose_name_plural': 'Даты экзамена ГИБДД',
                'ordering': ['order', 'exam_date'],
            },
        ),
        migrations.CreateModel(
            name='NormativeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Название')),
                ('file', models.FileField(blank=True, null=True, upload_to='normative_docs/', verbose_name='Файл')),
                ('external_link', models.URLField(blank=True, verbose_name='Внешняя ссылка')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name='Примечание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Нормативный документ',
                'verbose_name_plural': 'Нормативные документы',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_price', models.IntegerField(default=64000, verbose_name='Цена для студентов')),
                ('external_price', models.IntegerField(default=67000, verbose_name='Цена для сторонних')),
                ('student_initial_payment', models.IntegerField(default=10000, verbose_name='Первоначальный взнос студенты')),
                ('external_initial_payment', models.IntegerField(default=15000, verbose_name='Первоначальный взнос сторонние')),
                ('training_duration', models.CharField(default='3 месяца', max_length=100, verbose_name='Срок обучения')),
                ('category', models.CharField(default='В', max_length=10, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Стоимость обучения',
                'verbose_name_plural': 'Стоимость обучения',
            },
        ),
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название')),
                ('file', models.FileField(upload_to='regulations/', verbose_name='Файл')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Положение',
                'verbose_name_plural': 'Положения',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='8 917-236-95-35', max_length=100, verbose_name='Телефон')),
                ('address', models.CharField(default='г.Альметьевск, ул. Мира 10', max_length=300, verbose_name='Адрес')),
                ('office_room', models.CharField(default='№312', max_length=50, verbose_name='Кабинет записи')),
                ('work_hours', models.CharField(default='понедельник-пятница с 8:00 до 16:00 (обед с 12:00 до 13:00)', max_length=200, verbose_name='Время работы')),
                ('director_name', models.CharField(default='Алаев Владимир Петрович', max_length=200, verbose_name='Руководитель')),
                ('director_office', models.CharField(default='220 кабинет', max_length=50, verbose_name='Кабинет руководителя')),
                ('gosposhlina_link', models.URLField(blank=True, max_length=500, verbose_name='Ссылка для оплаты госпошлины')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='TaxReturnInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Содержание страницы (HTML)')),
            ],
            options={
                'verbose_name': 'Возврат 13%',
                'verbose_name_plural': 'Возврат 13%',
            },
        ),
        migrations.CreateModel(
            name='TheoreticalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info_text', models.TextField(default='Теоретические занятия проводятся 2 раза в неделю (понедельник-четверг) с 18:15 до 19:30, лекционные классы - 003, 023, компьютерные классы - 231, 233.', verbose_name='Текст расписания')),
                ('schedule_file', models.FileField(blank=True, null=True, upload_to='schedules/', verbose_name='Файл расписания (PDF/изображение)')),
                ('schedule_image', models.ImageField(blank=True, null=True, upload_to='schedules/', verbose_name='Изображение расписания')),
            ],
            options={
                'verbose_name': 'Расписание теории',
                'verbose_name_plural': 'Расписание теории',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=300, verbose_name='Подпись')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.gallerycategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.IntegerField(verbose_name='Номер группы')),
                ('max_students', models.IntegerField(default=28, verbose_name='Максимум студентов')),
                ('free_places', models.IntegerField(default=28, verbose_name='Свободных мест')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.enrollmentperiod', verbose_name='Период')),
            ],
            options={
                'verbose_name': 'Группа набора',
                'verbose_name_plural': 'Группы набора',
                'ordering': ['group_number'],
            },
        ),
    ]
